version: '3.3'

services:
  # server:
  #   image: poeschl/shoreline
  #   ports:
  #     - "5900:5900"
  #   command: -w 100 -h 100

  client1:
    image: ghcr.io/poeschl/pixelpwnr
    # depends_on:
    #   - server
    # links:
    #   - server:target
    volumes:
      - ./images:/images
    command: pixelflut.rc3.io:1234 -i /images/test1.png -x 1800 -y 490 -w 100 -h 100

  client2:
    image: ghcr.io/poeschl/pixelpwnr
    # depends_on:
    #   - server
    # links:
    #   - server:target
    volumes:
      - ./images:/images
    command: pixelflut.rc3.io:1234 -i /images/test1.png -x 1800 -y 490 -w 100 -h 100


